app_get_all_albums:
  pattern: /
  defaults: { _controller: AppBundle:Album:getAllAlbum }

app_get_single_album:
  pattern: /{slug}/songs
  defaults: { _controller: AppBundle:Album:getSingleAlbum }

app_add_album:
  pattern: /add
  defaults: { _controller: AppBundle:Album:addNewAlbum }