app_get_all_chords:
  pattern: /chord
  defaults: { _controller: AppBundle:Chord:getAllChords }

app_get_single_chord:
  pattern: /chord/{slug}
  defaults: { _controller: AppBundle:Chord:getSingleChord }
