app_add_comments:
  pattern: /news/{slug}/new
  defaults: { _controller: AppBundle:Comments:addComments }

app_json_comment:
    pattern: /{slug}/add
    defaults: { _controller: AppBundle:Comments:createComment}
    requirements:
            _method:  POST
