
#song
app_get_all_songs:
  pattern: /song
  defaults: { _controller: AppBundle:Song:getAllSong }

app_add_song:
  pattern: /add_song
  defaults: { _controller: AppBundle:Song:addSong }

app_get_single_song:
  pattern: /song/{slug}
  defaults: { _controller: AppBundle:Song:getSingleSong }