<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends DocumentRepository
{
    public function getIdArrayByName($name)
    {
        return $this->getDocumentManager()->createQueryBuilder($this->findByName($name))
            ->setQueryArray('name', '%'.$name.'%');
    }
}
