app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

user_routing:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

#memory_fos_user:
#    resource: "@UserBundle/Resources/config/routing.yml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login