app_news:
  resource: "@AppBundle/Resources/config/routings/news_routing.yml"
  prefix: /

app_album:
  resource: "@AppBundle/Resources/config/routings/album_routing.yml"
  prefix: /album

app_song:
  resource: "@AppBundle/Resources/config/routings/song_routing.yml"

app_video:
  resource: "@AppBundle/Resources/config/routings/video_routing.yml"

app_chord:
  resource: "@AppBundle/Resources/config/routings/chord_routing.yml"
