app:
    pattern:  /
    defaults: { _controller: AppBundle:News:index }

app_video_addVideo:
    pattern: /new
    defaults: { _controller: AppBundle:Video:addVideo}

app_video_copyVideoToUser:
    pattern: /copyVideo/{user_id}/{video_id}
    defaults: { _controller: AppBundle:Video:copyVideoToUser}

app_video_show:
    pattern: /showVideo
    defaults: { _controller: AppBundle:Video:showVideo}

app_chord_show:
    pattern: /showChord
    defaults: { _controller: AppBundle:Chord:index}

app_song_show:
    pattern: /showSong
    defaults: { _controller: AppBundle:Song:index}

app_song_show_by_album:
    pattern: /songInAlbum
    defaults: { _controller: AppBundle:Song:songsInAlbum}


app_album_show:
    pattern: /showAlbum
    defaults: { _controller: AppBundle:Album:index}

app_video_addSong:
    pattern: /addSong
    defaults: { _controller: AppBundle:Song:addSong}