#new routings

#album
app_get_all_albums:
  pattern: /album
  defaults: { _controller: AppBundle:Album:getAllAlbum }

app_get_single_album:
  pattern: /album/{slug}
  defaults: { _controller: AppBundle:Album:getSingleAlbum }

#chord
app_get_all_chords:
  pattern: /chord
  defaults: { _controller: AppBundle:Chord:getAllChords }

app_get_single_chord:
  pattern: /chord/{slug}
  defaults: { _controller: AppBundle:Chord:getSingleChord }

#news
app_get_all_news:
  pattern: /
  defaults: { _controller: AppBundle:News:getAllNews }

app_get_single_news:
  pattern: /news/{slug}
  defaults: { _controller: AppBundle:News:getSingleNews }

#video
app_get_all_videos:
  pattern: /video
  defaults: { _controller: AppBundle:Video:getAllVideos }

app_get_single_video:
  pattern: /video/{slug}
  defaults: { _controller: AppBundle:Video:getSingleVideo }