app:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }
app_videos_of_album:
    pattern: /album/{id}
    defaults: { _controller: AppBundle:Default:songsOfCategory}
app_video_addVideo:
    pattern: /addVideo
    defaults: { _controller: AppBundle:Default:addVideo}
app_video_copyVideoToUser:
    pattern: /copyVideo/{user_id}/{video_id}
    defaults: { _controller: AppBundle:Default:copyVideoToUser}
