<?php

namespace AppBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends NestedTreeRepository
{
}
