<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChordRepository extends EntityRepository
{
}
